### ISSUE TITLE
c8y sessions create: prompt an error message if --host is left out

### ISSUE THREAD

**Issue by scfx** [reubenmiller/go-c8y-cli#143]
when i create a new session with _c8y sessions create_ i am asked for a user name and password. however the json/session created is not usable as the host info is missing and has to be deleted manually.

Can we either add  an input for the host name of the session or prompt an error message if the host is left out?

**Comment by reubenmiller** [comment]
Thanks @scfx for find. Yes it looks to be a bug, the field is marked as required, but it is not throwing the appropriate error.

Shouldn't take long to fix, below are the suggested changes:

### Suggested changes

* Prompt for host if missing (but only if the console is not interactive, otherwise display "missing required parameter: host")
* Prompt for the session type (including description), e.g. dev, qual, prod. (also disable prompt when console is not interactive)

**Comment by reubenmiller** [comment]
The fix has been merged and will be included in the next release in the next few days
