### ISSUE TITLE
Unexpected progress bar when uploading a microservice

### ISSUE THREAD

**Issue by k-butz** [reubenmiller/go-c8y-cli#343]
Really more a cosmetical issue:
When uploading a Microservice via `c8y microservices create --file XYZ.zip -f` the progress bar is immediately at 100% with an elapsed time of 0 seconds - but the process to upload the binary takes longer. IIRC in earlier versions the bar was counting step by step and the command finished once the bar reached 100%.

Tested in version `2.39.2` using the `ghcr.io/reubenmiller/c8y-shell` .

**Comment by reubenmiller** [comment]
Do you know which version it was previously ok?

**Comment by k-butz** [comment]
Don't know the exact version it was introduced - but e.g. in version `v2.22.1` the progress bar works as expected.

**Comment by k-butz** [comment]
Tested a bit around, in `2.38.1` it was working as expected, the issue started to appear in `2.39.0`.

**Comment by reubenmiller** [comment]
> Tested a bit around, in `2.38.1` it was working as expected, the issue started to appear in `2.39.0`. 

I suspect the auto retry feature is affecting this...

**Comment by reubenmiller** [comment]
Investigating confirms that it is a problem with the retry feature which was introduced in `2.39.0` which uses the [go-retryablehttp](https://github.com/hashicorp/go-retryablehttp), however the library is more problematic than I first thought, as it will blindly load the entire body of the outgoing request into memory (due to part of its retry mechanism), for uploading large binaries this is obviously not ideal...

I'm checking if I can limit the "retry" feature to command which don't use binary uploading until I can come up with a better way to handle this...though if I can't create a short term workaround, I might just revert the "retry" feature all together...

**Comment by reubenmiller** [comment]
Included in [v2.39.3](https://github.com/reubenmiller/go-c8y-cli/releases/tag/v2.39.3) as the retries is now disabled by default which will not affect the progress bar.
