### ISSUE TITLE
Add-DeviceToGroup Cmdlet does not support object input for -Group parameter

### ISSUE THREAD

**Issue by ButKor** [reubenmiller/go-c8y-cli#42]
Summary: The Add-DeviceToGroup Cmdlet does not support a (group) ps object as input for the -Group parameter. (Seems it's not extracting the .id automatically)

Reproduction steps:
1) Create a group: $g = New-TestDeviceGroup
2) Create a device: $d = New-TestDevice
3) Assign $d to $g: Add-DeviceToGroup -Group $g -NewChildDevice $d
--> Error
Note that Add-DeviceToGroup -Group $g.id -NewChildDevice $d works.

Attached the verbose output.
![add-device-to-group](https://user-images.githubusercontent.com/20768097/106380954-f1afe900-63b5-11eb-87e1-d15b32f59876.png)

**Comment by reubenmiller** [comment]
This has been fixed in the newer v2 version of go-c8y-cli. The above example now works in PSc8y v2, however it is now advisable to use the native go-c8y-cli binary (c8y) instead of the PowerShell wrapper (PSc8y).

The new v2 version supports piping natively so there is no advantage of using PSc8y over the native c8y binary.
