### ISSUE TITLE
Use time from template when creating Alarms

### ISSUE THREAD

**Issue by goflo** [reubenmiller/go-c8y-cli#51]
Hi,

thanks for this nice tool!
I have an issue when creating alarms. Using the following command I want to create alarms for a bunch of devices:
`cat devices_10.json | c8y alarms create --template alarm_test.jsonnet`

The template looks like this:
```
{
    source: {
    	id: input.value.id
    },
    type: 'demo_TestError_' + _.Int(400000, 411999),
    text: 'This is a test alarm!',
    severity: 'MINOR',
    status: 'ACTIVE',
    time: _.Now('-' + _.Int(0, 100) + 'h')
}
```

This is working fine but the time property is always set to now() and the value from the template is ignored...
I think that is because I don't use the `--time` parameter in the command create command. And according to the help for this command is time set to now() per default when the parameter is not set.
Any chance to create some random timestamps for the time property?
Thanks!

**Comment by reubenmiller** [comment]
Yeah that definitely makes sense. I think I'll need to adjust the default value handling of the time field so that if it gets populated by either the --data or --template fields then it does not override it with the now() from the explicit --time argument.

As a workaround you could use the generic api command `c8y api —method post —uri /alarm/alarms —template mytemplate`. And since already have the source.id field set in your template then it should all just work.

Though just a tip, normally if you’re using the c8y alarms create command (or any other command with the —device argument), then you don’t need to set the source id in your template as the command will bind the piped data with source.id automatically. These fields which are marked with “accepts pipeline” (I borrowed this concept from powershell)

I’ll should be able to do a new release in the coming weeks with a more long term fix (and maybe a more useful diagram to help illustrate how the argument binding works especially in relation to piped data)

**Comment by goflo** [comment]
Thanks for the reply and the idea of using the `api` command. I will try that out!

**Comment by goflo** [comment]
@reubenmiller the workaround seems not to be working when I pipe in the device ids like this:
`"439612", "439395", "439392", "439482", "439484" | c8y api --method POST --url "/alarm/alarms" --template test_alarm.jsonnet`

I think the piped data is not used for the template?
Also reading the get the device data from the file (like in the example above) doesn't work.
It works when I set a static device id in the template and don't pipe any data to the command:
`c8y api --method POST --url "/alarm/alarms" --template test_alarm.jsonnet`

...but that is not helpful atm. Any other idea?
Thanks!

**Comment by ButKor** [comment]
Issue is here that the c8y api command maps the input to its --url, while your command passes certain IDs --> the IDs override your url parameter.  So above calls target the invalid endpoints https://[your-url]/439612, https://https://[your-url]/439395, etc.
Btw some tip: the --dry parameter is great help to debug such things. It shows you the endpoint, header and the actual payload - that's a convenient way to see if and how your input.value got mapped.

On your issue, I would do this in a quick script, here's an example in powershell using native c8y:
```
# read ids from file
cat ids.txt | ForEach-Object {
    c8y api --method POST --url "/alarm/alarms" --template mytemplate.jsonnet --templateVars "source_id=$_" --force
}

# or manually 
# "112800", "111805" | ForEach-Object {
#     c8y api --method POST --url "/alarm/alarms" --template mytemplate.jsonnet --templateVars "source_id=$_" --force
# }
```

The template used here:
```
{
    source: {
    	id: "" + var("source_id")
    },
    type: 'demo_TestError_' + _.Int(400000, 411999),
    text: 'This is a test alarm!',
    severity: 'MINOR',
    status: 'ACTIVE',
    time: _.Now('-' + _.Int(0, 100) + 'h')
}
```

**Comment by goflo** [comment]
@ButKor thanks for the tip.
It's working fine!

**Comment by reubenmiller** [comment]
@goflo, [v2.1.0](https://github.com/reubenmiller/go-c8y-cli/releases/tag/v2.1.0) was just released which supports setting the time field view the template (and some other minor improvements).

For example, taking the template from your example

```
{
    type: 'demo_TestError_' + _.Int(400000, 411999),
    text: 'This is a test alarm!',
    severity: 'MINOR',
    status: 'ACTIVE',
    time: _.Now('-' + _.Int(0, 100) + 'h')
}
```

It can be used like so (piping in an device id)

```sh
echo "12345" | c8y events create --template event.jsonnet
```

And it produces something like this:

```json
{
  "severity": "MINOR",
  "source": {
    "id": "12345"
  },
  "status": "ACTIVE",
  "text": "This is a test alarm!",
  "time": "2021-07-29T21:18:38.553+02:00",
  "type": "demo_TestError_400747"
}
```

The time will be retrieved from the template rather than the `--time` argument. Though if you do provide the `--time` argument as well, then it will overwrite the value in the template.

Note, the `source.id` is not required in the template (when using c8y events create), as the piped data is automatically mapped to the `source.id` for this command, and it can't be overridden in the template.

**Comment by goflo** [comment]
Thanks @reubenmiller for the information! I will check that. Have you changed that only for Alarms? I think the behaviour for Measurements is the same. I will update to 2.1.0 and give it a try ;-)

**Comment by reubenmiller** [comment]
@goflo I updated the behaviour in all time fields (and all other fields that i defined a default value, it was only about 10 flags i. total) so it should work for alarms, events and measurements
